### ISSUE TITLE
Location Examples Needed For Prepared By & Prepared For Sections

### ISSUE THREAD

**Issue by Gabeblis** [GSA/automate.fedramp.gov#105]
The documentation for Prepared By and Prepared For needs examples demonstrating the use of location assemblies. This is related to issues https://github.com/GSA/fedramp-automation/issues/861 and https://github.com/GSA/fedramp-automation/issues/862.

**Comment by aj-stein-gsa** [comment]
@Gabeblis can you update status from Ready to In-Review so people know to review this in the ever-growing review queue? 😅

**Comment by Gabeblis** [comment]
done!
