### ISSUE TITLE
Update December 4 OSCAL Implementers slide deck

### ISSUE THREAD

**Issue by jjahearn22** [GSA/automate.fedramp.gov#129]
We can have a topic discussion on Monday, here is the link to the deck: https://docs.google.com/presentation/d/1aP-UA_-ZfgjfRtxuCXQif15aCV4YkaSP/edit#slide=id.p1

**Comment by aj-stein-gsa** [comment]
Woops, I forgot to reviewed older issues, this upload of slides was tacked onto the initial work in https://github.com/GSA/automate.fedramp.gov/pull/73. We can close this as resolved now.
