### ISSUE TITLE
Complete 12.18 OSCAL Implementers Slide Deck

### ISSUE THREAD

**Issue by jjahearn22** [GSA/automate.fedramp.gov#136]
@Rene2mt & @aj-stein-gsa please fill in content in this slide deck by COB Monday (12/16). That way I can do quick edits and upload ahead of time on Tuesday.

https://docs.google.com/presentation/d/1xSsPgtCz-t8NDdQS-w-MfFo5ArwyOkqB/edit#slide=id.p1

**Comment by aj-stein-gsa** [comment]
We are going to push this back a day, as late as it is, I do know. @kyhu65867 is back from leave and agreed to work on this with/for us. 😄
