### ISSUE TITLE
Is Oscal Implementers the same as Data Bytes?

### ISSUE THREAD

**Issue by davaya** [GSA/automate.fedramp.gov#43]
Resources/Engage says: "The FedRAMP OSCAL Data Bites series is a monthly meeting space ..."

Is this replaced by a weekly Oscal Implementers meeting series or are they separate activities?  If the same, the paragraph should be updated, if separate the paragraph should mention both.

**Comment by aj-stein-gsa** [comment]
Hi @davaya, thanks for your issue. Is there something specific we can clear up regarding this request based upon content of the automate.fedramp.gov or were you asking more generally?

**Comment by aj-stein-gsa** [comment]
This issue should be covered by GSA/fedramp-automation#738 and #73 PR that will document some of the meeting structures. It should answer this question here so I will cross-link for review with final review of the PR and superset issue.

**Comment by aj-stein-gsa** [comment]
Sorry for the delayed update, @davaya. To quickly answer your question for good: no, they are not the same. Luckily for you, me, and the rest of the community, we added some explanation of this fact on their respective pages created as part of #73. They have slightly different audiences and cadences.

From [the Data Bytes page](https://automate.fedramp.gov/collaborate/meetings/data-bytes/):

> [What is it?](https://automate.fedramp.gov/collaborate/meetings/data-bytes/#what-is-it)
FedRAMP [created the Data Bytes meetings in August 2022](https://www.fedramp.gov/blog/2022-08-18-fedramp-launches-oscal-developer-data-bites-series/) for Cloud Service Providers (CSPs), federal agencies, and Third Party Assessment Organizations (3PAOs) to discuss technical topics regarding users’ utilization of OSCAL for FedRAMP, FedRAMP automation updates or changes, and other topics attendees choose in open forum conversations.
> 
> [How do I join?](https://automate.fedramp.gov/collaborate/meetings/data-bytes/#how-do-i-join)
You can sign up for this monthly meeting by [filling in this request form](https://docs.google.com/forms/d/1XgP_CZTfIh_ahdPJ6V2eBxIRCQ6wqT34ZFEWCApN9i4/edit).

From the [OSCAL Implementers page](https://automate.fedramp.gov/collaborate/meetings/implementers/):

> [What is it?](https://automate.fedramp.gov/collaborate/meetings/implementers/#what-is-it)
> FedRAMP [established the OSCAL Implementers meeting series in August 2024](https://www.fedramp.gov/updates/pilots/digital-authorization-package/) to collaborate with participants from cloud service providers (CSPs), governance, risk, and compliance (GRC) tool providers, and federal agencies to explore the use of the Open Security Controls Assessment Language (OSCAL) to create machine-readable, digital authorization packages. These bi-weekly meetings allow FedRAMP staff to directly collaborate with volunteers in the [Digital Authorization Package Pilot](https://www.fedramp.gov/updates/pilots/digital-authorization-package/).
>
> [How do I join?](https://automate.fedramp.gov/collaborate/meetings/implementers/#how-do-i-join)
Participants can find meeting information by [subscribing to the mailing list](https://www.fedramp.gov/updates/pilots/digital-authorization-package/#how-to-participate) and receive meeting invites.

I will close this issue for now. I hope that information helps.
