### ISSUE TITLE
SSP documentation does not cover user type

### ISSUE THREAD

**Issue by aj-stein-gsa** [GSA/automate.fedramp.gov#44]
I wanted to cross-reference the docs on the proper use of `/system-security-plan/user/prop/@type` but quickly skimmed and do not see mention of it on the updated docs. I am not sure priority or if it is urgent, but seems common enough we should consider adding explanation, even if we permit upstream NIST OSCAL allowed-values and do not have custom subset or different values altogether.

The context where this came up in PR review is in https://github.com/GSA/fedramp-automation/pull/634#discussion_r1737036377.

**Comment by Rene2mt** [comment]
@aj-stein-gsa PR GSA/automate.fedramp.gov/pull/62 closes this issue, right?
